name: Test and release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: install dependencies
      run: npm ci

      - name: run test suite
      run: npm test

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: install dependencies
        run: npm ci

      - name: run test suite
        run: npm run test

      - name: version and release
        run: npx semantic-release 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}